name: Publish NuGet

on:
  push:
    branches:
    - master
    
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.1.1

      - name: NuGet restore
        run: nuget restore IPC-2581.sln

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3

      - name: Build
        run: dotnet build IPC-2581/IPC-2581.csproj
      
      - name: NuGet pack
        run: nuget pack IPC-2581/IPC-2581.csproj -OutputDirectory nuget

      - name: NuGet publish
        run: nuget push nuget\**\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.NUGETKEY }}

